[package]
name        = "flix-htmldoc"
description = "A Flix combinator library to generate HTML."
version     = "0.4.2"
flix        = "0.67.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/flix-rosetree" = { version = "0.2.0", security = "unrestricted" }
"github:stephentetley/flix-pretty" = { version = "0.9.2", security = "unrestricted" }

